/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Classes.Conexao;
import Classes.Funcionario;
import Classes.FuncionarioDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JULIO
 */
public class TelaAtualizarFuncionario extends javax.swing.JFrame {

  /**
   * Creates new form TelaAtualizarFuncionario
   */
  private boolean vmanter_senha = true;
  private boolean vmanter_salario = true;
  private boolean vmanter_codigo = true;
  private boolean vmanter_nome = true;
  private final Connection conexao;

  public TelaAtualizarFuncionario() {
    initComponents();

    getContentPane().setBackground(new java.awt.Color(0, 0, 128));
    conexao = new Conexao().getConexao();

    try {
      PreparedStatement sttmt = conexao.prepareStatement(
        "SELECT * FROM funcionario;"
      );
      ResultSet rst = sttmt.executeQuery();
      FuncionarioDAO autor = new FuncionarioDAO();
      while (rst.next()) {
        String nome = rst.getString("nome");
        String codigo = rst.getString("codigo");

        DefaultTableModel modelo = (DefaultTableModel) tabela_funcionarios.getModel();
        modelo.addRow(new Object[] { codigo, nome });
      }
    } catch (Exception e) {
      System.out.println("Erro na consulta de funcionários: " + e);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    botao_voltar_menu = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tabela_funcionarios = new javax.swing.JTable();
    jLabel1 = new javax.swing.JLabel();
    area_codigo = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    deletar_usuario = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    area_senha_nova = new javax.swing.JTextField();
    area_nome_novo = new javax.swing.JTextField();
    area_codigo_novo = new javax.swing.JTextField();
    manter_codigo = new javax.swing.JButton();
    atualizar_codigo = new javax.swing.JButton();
    manter_senha = new javax.swing.JButton();
    atualizar_senha = new javax.swing.JButton();
    manter_nome = new javax.swing.JButton();
    atualizar_nome = new javax.swing.JButton();
    jLabel8 = new javax.swing.JLabel();
    area_salario_novo = new javax.swing.JTextField();
    manter_salario = new javax.swing.JButton();
    atualizar_salario = new javax.swing.JButton();
    jLabel9 = new javax.swing.JLabel();
    continuar = new javax.swing.JButton();
    botao_voltar_menu1 = new javax.swing.JButton();
    sair = new javax.swing.JButton();

    botao_voltar_menu.setText("<");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel4.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel4.setText("ATUALIZAR SITUAÇÃO DE UM FUNCIONÁRIO");

    tabela_funcionarios.setModel(
      new javax.swing.table.DefaultTableModel(
        new Object[][] {},
        new String[] { "CÓDIGO", "NOME" }
      )
    );
    jScrollPane1.setViewportView(tabela_funcionarios);

    jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
    jLabel1.setText("CÓDIGO DO FUNCIONÁRIO");

    jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("FUNCIONÁRIOS");

    jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("O QUE DESEJA FAZER?");

    deletar_usuario.setText("DELETAR");
    deletar_usuario.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          deletar_usuarioActionPerformed(evt);
        }
      }
    );

    jLabel5.setText("CÓDIGO NOVO");

    jLabel6.setText("SENHA NOVA");

    jLabel7.setText("NOME NOVO");

    manter_codigo.setText("MANTÊ-LA");
    manter_codigo.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          manter_codigoActionPerformed(evt);
        }
      }
    );

    atualizar_codigo.setText("ATUALIZAR");
    atualizar_codigo.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          atualizar_codigoActionPerformed(evt);
        }
      }
    );

    manter_senha.setText("MANTÊ-LA");
    manter_senha.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          manter_senhaActionPerformed(evt);
        }
      }
    );

    atualizar_senha.setText("ATUALIZAR");
    atualizar_senha.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          atualizar_senhaActionPerformed(evt);
        }
      }
    );

    manter_nome.setText("MANTÊ-LA");
    manter_nome.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          manter_nomeActionPerformed(evt);
        }
      }
    );

    atualizar_nome.setText("ATUALIZAR");
    atualizar_nome.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          atualizar_nomeActionPerformed(evt);
        }
      }
    );

    jLabel8.setText("SALÁRIO NOVO");

    manter_salario.setText("MANTÊ-LA");
    manter_salario.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          manter_salarioActionPerformed(evt);
        }
      }
    );

    atualizar_salario.setText("ATUALIZAR");
    atualizar_salario.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          atualizar_salarioActionPerformed(evt);
        }
      }
    );

    jLabel9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
    jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel9.setText("ATUALIZAR INFORMAÇÕES");

    continuar.setText("CONTINUAR");
    continuar.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          continuarActionPerformed(evt);
        }
      }
    );

    botao_voltar_menu1.setText("<");
    botao_voltar_menu1.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          botao_voltar_menu1ActionPerformed(evt);
        }
      }
    );

    sair.setText("X");
    sair.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          sairActionPerformed(evt);
        }
      }
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addComponent(botao_voltar_menu1)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      jLabel4,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(sair)
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addComponent(jLabel1)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(area_codigo)
                )
                .addComponent(
                  jLabel3,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addComponent(
                  deletar_usuario,
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGroup(
                      layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.TRAILING,
                          false
                        )
                        .addGroup(
                          javax.swing.GroupLayout.Alignment.LEADING,
                          layout
                            .createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED
                            )
                            .addComponent(area_salario_novo)
                        )
                        .addGroup(
                          javax.swing.GroupLayout.Alignment.LEADING,
                          layout
                            .createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED
                            )
                            .addComponent(area_nome_novo)
                        )
                        .addGroup(
                          javax.swing.GroupLayout.Alignment.LEADING,
                          layout
                            .createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED
                            )
                            .addComponent(
                              area_senha_nova,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              678,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                        .addGroup(
                          javax.swing.GroupLayout.Alignment.LEADING,
                          layout
                            .createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED
                            )
                            .addComponent(area_codigo_novo)
                        )
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addGroup(
                      layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addGroup(
                          layout
                            .createSequentialGroup()
                            .addComponent(manter_codigo)
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED
                            )
                            .addComponent(
                              atualizar_codigo,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              Short.MAX_VALUE
                            )
                        )
                        .addGroup(
                          javax.swing.GroupLayout.Alignment.TRAILING,
                          layout
                            .createSequentialGroup()
                            .addComponent(manter_senha)
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED
                            )
                            .addComponent(
                              atualizar_senha,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              133,
                              Short.MAX_VALUE
                            )
                        )
                        .addGroup(
                          layout
                            .createSequentialGroup()
                            .addGroup(
                              layout
                                .createParallelGroup(
                                  javax.swing.GroupLayout.Alignment.TRAILING,
                                  false
                                )
                                .addComponent(
                                  manter_salario,
                                  javax.swing.GroupLayout.Alignment.LEADING,
                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                  Short.MAX_VALUE
                                )
                                .addComponent(
                                  manter_nome,
                                  javax.swing.GroupLayout.Alignment.LEADING,
                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                  Short.MAX_VALUE
                                )
                            )
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED
                            )
                            .addGroup(
                              layout
                                .createParallelGroup(
                                  javax.swing.GroupLayout.Alignment.LEADING
                                )
                                .addComponent(
                                  atualizar_nome,
                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                  133,
                                  Short.MAX_VALUE
                                )
                                .addComponent(
                                  atualizar_salario,
                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                  Short.MAX_VALUE
                                )
                                .addComponent(
                                  continuar,
                                  javax.swing.GroupLayout.Alignment.TRAILING,
                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                  Short.MAX_VALUE
                                )
                            )
                        )
                    )
                )
                .addComponent(
                  jLabel2,
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addComponent(
                  jScrollPane1,
                  javax.swing.GroupLayout.Alignment.TRAILING
                )
                .addComponent(
                  jLabel9,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
            )
            .addContainerGap()
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(
                  jLabel4,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  50,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(botao_voltar_menu1)
                .addComponent(sair)
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              jScrollPane1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              97,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(
                  area_codigo,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(deletar_usuario)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel9)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(
                  area_codigo_novo,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(manter_codigo)
                .addComponent(atualizar_codigo)
            )
            .addGap(18, 18, 18)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(
                  area_senha_nova,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(manter_senha)
                .addComponent(atualizar_senha)
            )
            .addGap(18, 18, 18)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(
                  area_nome_novo,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(manter_nome)
                .addComponent(atualizar_nome)
            )
            .addGap(18, 18, 18)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createParallelGroup(
                      javax.swing.GroupLayout.Alignment.BASELINE
                    )
                    .addComponent(manter_salario)
                    .addComponent(atualizar_salario)
                )
                .addGroup(
                  layout
                    .createParallelGroup(
                      javax.swing.GroupLayout.Alignment.BASELINE
                    )
                    .addComponent(jLabel8)
                    .addComponent(
                      area_salario_novo,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.RELATED,
              40,
              Short.MAX_VALUE
            )
            .addComponent(continuar)
            .addContainerGap()
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void deletar_usuarioActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_deletar_usuarioActionPerformed
    // TODO add your handling code here:
    FuncionarioDAO funcionario = new FuncionarioDAO();
    int id = funcionario.procurarFuncionarioCodigo(area_codigo.getText());

    if (id > 0) {
      funcionario.deletarFuncionario(id);
      TelaAtualizarFuncionario tela = new TelaAtualizarFuncionario();
      tela.setVisible(true);
    } else {}
  } //GEN-LAST:event_deletar_usuarioActionPerformed

  private void manter_codigoActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_manter_codigoActionPerformed
    // TODO add your handling code here:
    vmanter_codigo = true;
  } //GEN-LAST:event_manter_codigoActionPerformed

  private void atualizar_codigoActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_atualizar_codigoActionPerformed
    // TODO add your handling code here:
    vmanter_codigo = false;
  } //GEN-LAST:event_atualizar_codigoActionPerformed

  private void manter_senhaActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_manter_senhaActionPerformed
    // TODO add your handling code here:
    vmanter_senha = true;
  } //GEN-LAST:event_manter_senhaActionPerformed

  private void atualizar_senhaActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_atualizar_senhaActionPerformed
    // TODO add your handling code here:
    vmanter_senha = false;
  } //GEN-LAST:event_atualizar_senhaActionPerformed

  private void manter_nomeActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_manter_nomeActionPerformed
    // TODO add your handling code here:
    vmanter_nome = true;
  } //GEN-LAST:event_manter_nomeActionPerformed

  private void atualizar_nomeActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_atualizar_nomeActionPerformed
    // TODO add your handling code herse:
    vmanter_nome = false;
  } //GEN-LAST:event_atualizar_nomeActionPerformed

  private void manter_salarioActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_manter_salarioActionPerformed
    // TODO add your handling code here:
    vmanter_salario = true;
  } //GEN-LAST:event_manter_salarioActionPerformed

  private void atualizar_salarioActionPerformed(
    java.awt.event.ActionEvent evt
  ) { //GEN-FIRST:event_atualizar_salarioActionPerformed
    // TODO add your handling code here:
    vmanter_senha = false;
  } //GEN-LAST:event_atualizar_salarioActionPerformed

  private void continuarActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_continuarActionPerformed
    // TODO add your handling code here:
    FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
    int id = funcionarioDAO.procurarFuncionarioCodigo(area_codigo.getText());
    Funcionario funcionario;
    funcionario = funcionarioDAO.pegarFuncionario(id);

    if (!vmanter_codigo) {
      funcionario.setCodigo(area_codigo_novo.getText());
    }
    if (!vmanter_nome) {
      funcionario.setNome(area_nome_novo.getText());
    }
    if (!vmanter_salario) {
      funcionario.setSalario(Double.parseDouble(area_salario_novo.getText()));
    }
    if (!vmanter_senha) {
      funcionario.setSenha(area_senha_nova.getText());
    }
    boolean situacao = funcionarioDAO.atualizarFuncionario(funcionario, id);
    if (situacao) {
      TelaAtualizarFuncionario tela = new TelaAtualizarFuncionario();
      tela.setVisible(true);
    } else {
      JOptionPane.showMessageDialog(
        null,
        "ALGUM ERRO ENCONTRADO",
        "ALERTA",
        JOptionPane.ERROR_MESSAGE
      );
    }
  } //GEN-LAST:event_continuarActionPerformed

  private void botao_voltar_menu1ActionPerformed(
    java.awt.event.ActionEvent evt
  ) { //GEN-FIRST:event_botao_voltar_menu1ActionPerformed
    // TODO add your handling code here:
    MenuPrincipal tela = new MenuPrincipal();
    tela.setVisible(true);
  } //GEN-LAST:event_botao_voltar_menu1ActionPerformed

  private void sairActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_sairActionPerformed
    // TODO add your handling code here:
    System.exit(0);
  } //GEN-LAST:event_sairActionPerformed

  /**
   * @param args the command line arguments
   */

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField area_codigo;
  private javax.swing.JTextField area_codigo_novo;
  private javax.swing.JTextField area_nome_novo;
  private javax.swing.JTextField area_salario_novo;
  private javax.swing.JTextField area_senha_nova;
  private javax.swing.JButton atualizar_codigo;
  private javax.swing.JButton atualizar_nome;
  private javax.swing.JButton atualizar_salario;
  private javax.swing.JButton atualizar_senha;
  private javax.swing.JButton botao_voltar_menu;
  private javax.swing.JButton botao_voltar_menu1;
  private javax.swing.JButton continuar;
  private javax.swing.JButton deletar_usuario;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JButton manter_codigo;
  private javax.swing.JButton manter_nome;
  private javax.swing.JButton manter_salario;
  private javax.swing.JButton manter_senha;
  private javax.swing.JButton sair;
  private javax.swing.JTable tabela_funcionarios;
  // End of variables declaration//GEN-END:variables
}
